#!/usr/bin/bash

# Check for root
if [[ $EUID -ne 0 ]]; then
	echo "Please run this as root"
	exit 1
fi


# Mounting and binding stuff

cd /home/phablet/Desktop/kalich;

chroot kalifs;

echo "Kalifs mounted and ready to go";
