#!/bin/bash

# Check for root
if [[ $EUID -ne 0 ]]; then
	echo "Please run this as root"
	exit 1
fi

# Mount / as read/write
sudo mount -o remout,rw /;

# Run killkali if its a upgrade and chroot runs
killkali

# Before starting lets clean up older files that user may have around
rm -rf /usr/bin/killkali;
rm -rf /usr/bin/mountkali;
rm -rf /usr/bin/chkali;

# Delete old kali chroot
rm -rf /home/phablet/Desktop/kalich;

# Just in case someone used older script
rm -rf /usr/bin/kalich;

# Start of the script

echo "#";
echo "# Doing some preparation";
echo "#";

apt update;
apt insall -y wget curl;

echo "#";
echo "# Starting chroot preparation";
echo "#";

cd /home/phablet/Desktop;
mkdir kalich;
cd kalich;
wget https://build.nethunter.com/kalifs/kalifs-latest/kalifs-arm64-minimal.tar.xz;
mv kalifs-arm64-minimal.tar.xz kalifs.tar.xz;
echo "This will take some time so please wait...";
tar --numeric-owner -xpf kalifs.tar.xz;

rm -rf kalifs.tar.xz
mv kali-arm64 kalifs

echo "#";
echo "# Downloading some scripts for mounting chroot";
echo "#";

wget https://github.com/Martini-Lab/misc/raw/main/killkali;
wget https://github.com/Martini-Lab/misc/raw/main/mountkali;
wget https://github.com/Martini-Lab/misc/raw/main/chkali;

chmod +x killkali;
chmod +x mountkali;
chmod +x chkali;


mv killkali /usr/bin/killkali;
mv mountkali /usr/bin/mountkali;
mv chkali /usr/bin/chkali;
