#!/bin/bash

# Check for root
if [[ $EUID -ne 0 ]]; then
	echo "Please run this as root"
	exit 1
fi

# Start of the script

echo "#";
echo "# Doing some preparation";
echo "#";

sudo mount -o remout,rw /;
sudo apt update;
sudo apt insall -y wget curl;

echo "#";
echo "# Starting chroot preparation";
echo "#";

cd /home/phablet/Desktop;
mkdir kalich;
wget https://build.nethunter.com/kalifs/kalifs-latest/kalifs-arm64-minimal.tar.xz;
mv kalifs-arm64-minimal.tar.xz kalifs.tar.xz;
echo "This will take sme time so please wait...";
sudo tar --numeric-owner -xpf kalifs.tar.xz;

echo "#";
echo "# Downloading some scripts for mounting chroot";
echo "#";

wget https://github.com/Martini-Lab/misc/raw/main/killkali;
wget https://github.com/Martini-Lab/misc/raw/main/mountkali;
wget https://github.com/Martini-Lab/misc/raw/main/kalich;

chmod +x killkali;
chmod +x mountkali;
chmod +x kalich;


mv killkali /usr/bin/killkali;
mv mountkali /usr/bin/mountkali;
mv kalich /usr/bin/kalich;
