#!/usr/bin/bash

# Check for root
if [[ $EUID -ne 0 ]]; then
	echo "Please run this as root"
	exit 1
fi

# Unmounting and unbinding stuff

cd /home/phablet/Desktop/kalich

umount kalifs/proc
umount kalifs/sys
umount kalifs/dev

echo "Kali chroot killed, goodbye"
