#!/bin/bash

# Check for root
if [[ $EUID -ne 0 ]]; then
	echo "Please run this as root"
	exit 1
fi

# Unmounting and unbinding stuff

umount /home/phablet/Desktop/kalich/kalifs/proc
umount /home/phablet/Desktop/kalich/kalifs/sys
umount /home/phablet/Desktop/kalich/kalifs/dev

echo "Kali chroot killed, goodbye"
