#!/bin/bash

# Check for root
if [[ $EUID -ne 0 ]]; then
	echo "Please run this as root"
	exit 1
fi

# Mounting and binding stuff

cd /home/phablet/Desktop/kalich;

mount -t proc proc kalifs/proc;
mount -t sysfs sys kalifs/sys;
mount -o bind /dev kalifs/dev;

echo "Kalifs mounted and ready to go";
