#!/bin/bash

# Check for root
if [[ $EUID -ne 0 ]]; then
	echo "Please run this as root"
	exit 1
fi

# Mounting and binding stuff

mount -t proc proc /home/phablet/Desktop/kalich/kalifs/proc;
mount -t sysfs sys /home/phablet/Desktop/kalich/kalifs/sys;
mount -o bind /dev /home/phablet/Desktop/kalich/kalifs/dev;

echo "Kalifs mounted and ready to go";
